workflows:
  android_aab:
    name: Build Android AAB (Flutter 3.22.3, Java 17)
    environment:
      flutter: 3.22.3
      java: 17

    scripts:
      - name: Flutter version
        script: |
          flutter --version

      - name: Clean project
        script: |
          flutter clean

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build Android App Bundle (release)
        script: |
          flutter build appbundle --release --no-shrink

    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
